events:
  test_video:
    name: Test
    type: PlayVideo
    # schedule string follows syntax of https://github.com/dbader/schedule
    schedule: every().day.at("12:02:55")
    # schedule: every(3).minutes
    url: file:///Users/fsc/Desktop/video.mp4