events:
  test_video:
    name: Test
    type: PlayVideo
    schedule: every(16).seconds
    start: 0
    fullscreen: false
    geometry: [100, 100, 300, 300]
    url: file:///Users/fsc/Downloads/jsjsjs.mp4
  test_video2:
    name:: Neden02
    type: PlayVideo
    schedule: every(7).seconds
    start: 40
    url: file:///Users/fsc/Downloads/jsjsjs.mp4
